In [1]:
import pandas as pd

In [2]:
data={
    "Assessment":["Good","Average","Good","Poor","Good",
                  "Average","Good","Poor","Average","Good"],
    "Assignment":["Yes","Yes","No","No","Yes","No","No","Yes","No","Yes"],
    "Project":["Yes","No","Yes","No","Yes","Yes","No","Yes","No","Yes"],
    "Result (%)":[95,70,75,45,98,80,75,65,58,89]
}
data=pd.DataFrame(data)

In [3]:
data

  Assessment Assignment Project  Result (%)
0       Good        Yes     Yes          95
1    Average        Yes      No          70
2       Good         No     Yes          75
3       Poor         No      No          45
4       Good        Yes     Yes          98
5    Average         No     Yes          80
6       Good         No      No          75
7       Poor        Yes     Yes          65
8    Average         No      No          58
9       Good        Yes     Yes          89

In [4]:
# Standard deviation
std_gen=round(data["Result (%)"].std(),4)
std_gen

np.float64(16.5462)

In [5]:
std_reduction_list=[]

In [6]:
def std_func(list_,col):
    total_attribute_std=[]
    for val in list_:
        a=data[col]==val
        print(val)
        temp_table=data.loc[a]
        print(temp_table)
        std_=round(temp_table["Result (%)"].std(),4)
        print(f"std: {std_}")
        n=temp_table[col].count()
        std_val=(n/10)*std_
        total_attribute_std.append(std_val)
        # print(f"std: {total_attribute_std}")
        print()
    sum_std=round(sum(total_attribute_std),4)
    print(f"weighted standard deviation: {sum_std}")
    std_reduction=round((std_gen-sum_std),4)
    print(f"Standard deviation reduction {std_reduction}")
    std_reduction_list.append({
        "Attribute":col,
        "std_reduction":std_reduction
    })
    display(pd.DataFrame(std_reduction_list))
    print()

In [7]:
# For Assessment column
std_func(["Good","Average","Poor"],"Assessment")

Good
  Assessment Assignment Project  Result (%)
0       Good        Yes     Yes          95
2       Good         No     Yes          75
4       Good        Yes     Yes          98
6       Good         No      No          75
9       Good        Yes     Yes          89
std: 10.8995

Average
  Assessment Assignment Project  Result (%)
1    Average        Yes      No          70
5    Average         No     Yes          80
8    Average         No      No          58
std: 11.0151

Poor
  Assessment Assignment Project  Result (%)
3       Poor         No      No          45
7       Poor        Yes     Yes          65
std: 14.1421

weighted standard deviation: 11.5827
Standard deviation reduction 4.9635

    Attribute  std_reduction
0  Assessment         4.9635

In [8]:
# For Assignemt column
std_func(["Yes","No"],"Assignment")

Yes
  Assessment Assignment Project  Result (%)
0       Good        Yes     Yes          95
1    Average        Yes      No          70
4       Good        Yes     Yes          98
7       Poor        Yes     Yes          65
9       Good        Yes     Yes          89
std: 14.9766

No
  Assessment Assignment Project  Result (%)
2       Good         No     Yes          75
3       Poor         No      No          45
5    Average         No     Yes          80
6       Good         No      No          75
8    Average         No      No          58
std: 14.6731

weighted standard deviation: 14.8248
Standard deviation reduction 1.7214

    Attribute  std_reduction
0  Assessment         4.9635
1  Assignment         1.7214

In [9]:
std_func(["Yes","No"],"Project")

Yes
  Assessment Assignment Project  Result (%)
0       Good        Yes     Yes          95
2       Good         No     Yes          75
4       Good        Yes     Yes          98
5    Average         No     Yes          80
7       Poor        Yes     Yes          65
9       Good        Yes     Yes          89
std: 12.6438

No
  Assessment Assignment Project  Result (%)
1    Average        Yes      No          70
3       Poor         No      No          45
6       Good         No      No          75
8    Average         No      No          58
std: 13.3915

weighted standard deviation: 12.9429
Standard deviation reduction 3.6033

    Attribute  std_reduction
0  Assessment         4.9635
1  Assignment         1.7214
2     Project         3.6033